# Site settings
title: Frank Noirot
email: mailto:frank@franknoirot.co
author: Frank RJ Noirot
description: A simple portfolio site for Frank Noirot, a designer based in Washington DC and NYC.
url: franknoirot.co
github: https://www.github.com/franknoirot
instagram: https://www.instagram.com/franknoirot


# Portfolio collection
collections:
  portfolio:
    output: true
    permalink: /:collection/:title

# Files to excludes from your website
exclude:
  - .gitignore
  - CNAME

# plugins:
#   - jekyll-sitemap
